all:
	$(MAKE) -C sportvACTS/generator
	$(MAKE) -C sportvACTS
	$(MAKE) -C gueltigesDatum
	$(MAKE) -C max3
	$(MAKE) -C statistikDB
	$(MAKE) -C rabatt
	$(MAKE) -C gtest
	$(MAKE) -C zufallstest
	$(MAKE) -C syntax/datum
	$(MAKE) -C syntax/iban/ibanpruefung
	$(MAKE) -C syntax/iban
	$(MAKE) -C ctc/max3
	$(MAKE) -C ctc/undoder
	$(MAKE) -C bubblesort/istaufsteigendsortiert
	$(MAKE) -C bubblesort
	$(MAKE) -C fahrstuhl
	$(MAKE) -C taxi2
	$(MAKE) -C gcov/max3
	$(MAKE) -C gcov/fahrstuhl
	$(MAKE) -C gcov/vokale
	$(MAKE) -C gcov/undoder
	$(MAKE) -C klausur
	$(MAKE) -C sportverein
	$(MAKE) -C taxi1
clean:
	$(MAKE) -C sportvACTS/generator clean
	$(MAKE) -C sportvACTS clean
	$(MAKE) -C gueltigesDatum clean
	$(MAKE) -C max3 clean
	$(MAKE) -C statistikDB clean
	$(MAKE) -C rabatt clean
	$(MAKE) -C gtest clean
	$(MAKE) -C zufallstest clean
	$(MAKE) -C syntax/datum clean
	$(MAKE) -C syntax/iban/ibanpruefung clean
	$(MAKE) -C syntax/iban clean
	$(MAKE) -C ctc/max3 clean
	$(MAKE) -C ctc/undoder clean
	$(MAKE) -C bubblesort/istaufsteigendsortiert clean
	$(MAKE) -C bubblesort clean
	$(MAKE) -C fahrstuhl clean
	$(MAKE) -C taxi2 clean
	$(MAKE) -C gcov/max3 clean
	$(MAKE) -C gcov/fahrstuhl clean
	$(MAKE) -C gcov/vokale clean
	$(MAKE) -C gcov/undoder clean
	$(MAKE) -C klausur clean
	$(MAKE) -C sportverein clean
	$(MAKE) -C taxi1 clean
